name: "Migrate Pacakges"
description: "Migrate packages from one org to another, Expects to run under Debian/Ubuntu"
inputs:
  GH_SOURCE_PAT:
    description: The PAT for the source repo
    required: true
  GH_TARGET_PAT:
    description: The PAT for the source repo
    required: true
  source_host:
    description: The source instance to migrate from
    required: false
    default: github.com
  source_org:
    description: The source org to migrate from
    required: true
  target_host:
    description: The target instance to migrate to
    required: false
    default: github.com
  target_org:
    description: The target org to migrate to
    required: true
  type:
    description: 'type of migration to do: "all", "maven", "npm", "nuget", "container". Ruby gems migration not implemented'
    required: false
    default: "all"
runs:
  using: "composite"
  steps:
    - name: set up action
      run: chmod +x ${{ github.action_path }}/scripts/*.s
      shell: bash

    - name: Start maven section
      shell: bash
      run: echo "--- MAVEN -----------------------------------------------------------------------------------------------------------------"
      if: ${{ contains(inputs.type, 'all') || contains(input.type, 'maven') }}

    - name: Migrate maven packages
      run: |
        ${{ github.action_path }}/scripts/migrate-maven-packages-between-github-instances.sh ${{ inputs.source_org }} ${{ inputs.source_host }} ${{ inputs.target_org }} ${{ inputs.target_host }}
      id: migrate-mvn
      shell: bash
      if: ${{ contains(inputs.type, 'all') || contains(input.type, 'maven') }}
      env:
        GH_SOURCE_PAT: ${{ inputs.GH_SOURCE_PAT }}
        GH_TARGET_PAT: ${{ inputs.GH_TARGET_PAT }}

    - name: End maven section
      shell: bash
      if: ${{ contains(inputs.type, 'all') || contains(input.type, 'maven') }}
      run: echo "--- END MAVEN -------------------------------------------------------------------------------------------------------------"
    
    - name: Start NPM section
      shell: bash
      if: ${{ contains(inputs.type, 'all') || contains(input.type, 'npm') }}
      run: echo "--- NPM -------------------------------------------------------------------------------------------------------------------"

    - name: Migrate NPM packages
      run: |
        ${{ github.action_path }}/scripts/migrate-npm-packages-between-github-instances.sh ${{ inputs.source_org }} ${{ inputs.source_host }} ${{ inputs.target_org }} ${{ inputs.target_host }}
      id: migrate-npm
      if: ${{ contains(inputs.type, 'all') || contains(input.type, 'npm') }}
      shell: bash
      env:
        GH_SOURCE_PAT: ${{ inputs.GH_SOURCE_PAT }}
        GH_TARGET_PAT: ${{ inputs.GH_TARGET_PAT }}

    - name: End NPM section
      shell: bash
      if: ${{ contains(inputs.type, 'all') || contains(input.type, 'npm') }}
      run: echo "--- END NPM ---------------------------------------------------------------------------------------------------------------"

    - name: Start nuget section
      shell: bash
      if: ${{ contains(inputs.type, 'all') || contains(input.type, 'nuget') }}
      run: echo "--- NUGET -----------------------------------------------------------------------------------------------------------------"

    - name: Migrate nuget packages
      run: |
        ${{ github.action_path }}/scripts/migrate-nuget-packages-between-orgs.sh ${{ inputs.source_org }} ${{ inputs.source_host }} ${{ inputs.target_org }}
      id: migrate-nuget
      if: ${{ contains(inputs.type, 'all') || contains(input.type, 'nuget') }}
      shell: bash
      env:
        GH_SOURCE_PAT: ${{ inputs.GH_SOURCE_PAT }}
        GH_TARGET_PAT: ${{ inputs.GH_TARGET_PAT }}

    - name: End nuget section
      shell: bash
      if: ${{ contains(inputs.type, 'all') || contains(input.type, 'nuget') }}
      run: echo "--- END NUGET -------------------------------------------------------------------------------------------------------------"

    - name: End nuget section
      shell: bash
      if: ${{ contains(inputs.type, 'all') || contains(input.type, 'container') }}
      run: echo "--- CONTAINERS ------------------------------------------------------------------------------------------------------------"

    - name: migrate containers
      run: |
        ${{ github.action_path }}/scripts/migrate-container-packages-between-orgs.sh ${{ inputs.source_org }} ${{ inputs.source_host }} ${{ inputs.target_org }} ${{ inputs.target_host }}
      if: ${{ contains(inputs.type, 'all') || contains(input.type, 'container') }}
      id: migrate-containers
      shell: bash
      env:
        GH_SOURCE_PAT: ${{ inputs.GH_SOURCE_PAT }}
        GH_TARGET_PAT: ${{ inputs.GH_TARGET_PAT }}
